AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: >
  Self-Healing-Infra

  Sample SAM Template for Self-Healing-Infra

Globals:
  Function:
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON

Resources:

  DiagnoseWithBedrockFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/zaman/diagnose-with-bedrock/
      Handler: index.handler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Timeout: 30

  ApplyFixFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/jyotish/apply-fix/
      Handler: index.handler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Timeout: 30

  AskAboutIncidentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/jyotish/ask-about-incidents/
      Handler: index.handler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Timeout: 30

  IncidentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SelfHealingIncidents
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: incidentId
          AttributeType: S
      KeySchema:
        - AttributeName: incidentId
          KeyType: HASH

  SelfHealingTestAlarm:
    Type: AWS::CloudWatch::Alarm
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AlarmName: SelfHealing-Test-Alarm
      Namespace: AWS/Lambda
      MetricName: Invocations
      Dimensions:
        - Name: FunctionName
          Value: Self-Healing-Infra-DiagnoseWithBedrockFunction-VRqzzWffBPM1
      Statistic: Average
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing

  SelfHealingTrigger:
    Type: AWS::Events::Rule
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: SelfHealingTrigger
      Description: Triggers self-healing workflow when infrastructure metrics breach thresholds
      EventBusName: default
      State: ENABLED
      EventPattern:
        source:
          - aws.cloudwatch
        detail-type:
          - CloudWatch Alarm State Change
        detail:
          state:
            value:
              - ALARM
      Targets:
        - Id: Iddfa1de24-3c4b-4c13-9a04-cdeb9f222556
          Arn: arn:aws:states:ap-south-1:691588646018:stateMachine:Self-Healing-Orchestrator
          RoleArn: arn:aws:iam::691588646018:role/service-role/Amazon_EventBridge_Invoke_Step_Functions_1487815626

  SelfHealingOrchestrator:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: Self-Healing-Orchestrator
      DefinitionUri: statemachine/orchestrator.asl.json
      DefinitionSubstitutions:
        DiagnoseFunctionArn: !GetAtt DiagnoseWithBedrockFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref DiagnoseWithBedrockFunction

        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt IncidentsTable.Arn