const value = (v) => v === undefined || v === null || v === '' ? 'Not available' : String(v);
const title = (v) => value(v).replaceAll('_', ' ');
const field = (i, camel, snake) => i[camel] ?? i[snake];

export default function IncidentCard({ incident, onDecision }) {
  const awaiting = incident.status === 'AWAITING_APPROVAL';
  const confidence = field(incident, 'confidence', 'confidence_score');
  const blast = field(incident, 'blastRadius', 'blast_radius');
  return <article className="incident-card"><div className="card-top"><div><span className={`severity ${String(incident.severity || 'unknown').toLowerCase()}`}>{title(incident.severity)}</span><h2>{value(incident.incidentId)}</h2><p>{value(incident.resourceType)} · {value(incident.resourceId)}</p></div><span className="status">{title(incident.status)}</span></div><div className="metrics"><div><small>Metric</small><b>{value(incident.metric)}</b></div><div><small>Observed / threshold</small><b>{value(incident.metricValue)} / {value(incident.threshold)}</b></div><div><small>Diagnosed</small><b>{incident.diagnosedAt ? new Date(incident.diagnosedAt).toLocaleString() : 'Not available'}</b></div></div><div className="diagnosis"><section><small>Root cause</small><p>{value(incident.rootCause)}</p></section><section><small>Why this action</small><p>{value(incident.reason)}</p></section><section><small>Recommended action</small><p>{value(incident.recommendedAction)}</p></section></div><div className="ai-grid"><div><small>AI confidence</small><b>{confidence === undefined ? 'Not available' : `${confidence}%`}</b><p>{value(field(incident, 'confidenceReason', 'confidence_reason'))}</p></div><div><small>Blast radius</small><b>{title(blast)}</b><p>{value(field(incident, 'blastRadiusReason', 'blast_radius_reason'))}</p></div><div><small>Estimated cost impact</small><b>{value(field(incident, 'estimatedCostImpact', 'estimated_cost_impact'))}</b></div></div>{incident.rejectionReason && <div className="reason"><b>Rejection reason:</b> {incident.rejectionReason}</div>}<div className="card-actions">{awaiting ? <><button onClick={() => onDecision(incident, 'reject')}>Reject</button><button className="primary" onClick={() => onDecision(incident, 'approve')}>Approve fix</button></> : <span>Decision: {value(incident.approvedBy || incident.rejectedBy)}</span>}</div></article>;
}
